Auth:
  ParseHttpPort: 80
  ParsePath: /auth
  SignRpcPort: 8181

  # 签发配置信息
  SignInfo:
    Secret: "3a^&1g*sxu12oihdi!hakjbd18@ahd"
    Timeout: 2 #hours
    Issuer: "auth-server"
    Audience: "auth.storeming.com"
