Auth:
  ParseHttpPort: 80
  ParsePath: /auth
  SignRpcPort: 8181

  # 签发配置信息
  SignInfo:
    Secret: "3a^&1g*sxu12oihdi!hakjbd18@ahd"
    Timeout: 2 #hours
    Issuer: "auth-server"
    Audience: "auth.storeming.com"

ParseLog:
  # Path log file output location
  Path: parse_server.log
  # Level log output level
  Level: info
  # Formatter test or json
  Formatter: json
  # Output os or file
  Output: file

SignLog:
  # Path log file output location
  Path: sign_server.log
  # Level log output level
  Level: info
  # Formatter test or json
  Formatter: json
  # Output os or file
  Output: file