#FROM centos
#MAINTAINER "xinmaozhu@foxmail.com"
#
#WORKDIR /auth
#COPY . /auth
#
#EXPOSE 80
#
#CMD ./api/parse_server


FROM centos
MAINTAINER "xinmaozhu@foxmail.com"

WORKDIR /auth
COPY . /auth

EXPOSE 8181

CMD ./api/sign_server
